name: Build project

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-debug:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2

    - name: Set up CMake project
      run: |
        .\scripts\setup.ps1 `
          -DCMAKE_BUILD_TYPE=Release `
          -DABIT_CI_BUILD=on

    - name: Build project
      run: |
        .\scripts\build.ps1

    - name: Upload artifacts
      uses: actions/upload-artifact@v2.2.2
      with:
        name: AByteInTime-unstable
        path: build/bin/Release