name: Build project

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-debug:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3

    - name: Compute variables
      id: vars
      run: |
        $env:GITHUB_OUTPUT += "sha_short=" + (git rev-parse --short HEAD) + "`n"

    - name: Set up CMake project
      run: |
        .\scripts\setup.ps1 `
          -DCMAKE_BUILD_TYPE=Debug `
          -DABIT_CI_BUILD=on

    - name: Build project
      run: |
        .\scripts\build.ps1

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: AByteInTime-Debug-${{ steps.vars.outputs.sha_short }}
        path: build/bin/Release

  build-release:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3

    - name: Compute variables
      id: vars
      run: |
        $env:GITHUB_OUTPUT += "sha_short=" + (git rev-parse --short HEAD) + "`n"

    - name: Set up CMake project
      run: |
        .\scripts\setup.ps1 `
          -DCMAKE_BUILD_TYPE=Release `
          -DABIT_CI_BUILD=on

    - name: Build project
      run: |
        .\scripts\build.ps1

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: AByteInTime-Release-${{ steps.vars.outputs.sha_short }}
        path: build/bin/Release