name: Build project

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-debug:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3

    - name: Set up and build project
      run: |
        .\scripts\setup.ps1 `
          -DCMAKE_BUILD_TYPE=Debug `
          -DABIT_CI_BUILD=on
        .\scripts\build.ps1

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: AByteInTime-Debug-unstable
        path: build/bin/Debug

  build-release:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3

    - name: Set up and build project
      run: |
        .\scripts\setup.ps1 `
          -DCMAKE_BUILD_TYPE=Release `
          -DABIT_CI_BUILD=on
        .\scripts\build.ps1

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: AByteInTime-Release-unstable
        path: build/bin/Release